const quotes = [
  "Success is the sum of small efforts repeated daily.",
  "Dream big, work hard, stay consistent.",
  "Discipline beats motivation every time.",
  "The best time to start was yesterday. The next best time is now.",
  "Your only limit is your mindset.",
  "Stay focused and never give up.",
  "Small progress is still progress.",
  "Don't watch the clock; keep moving.",
  "Hard work always pays off.",
  "Failure is a lesson, not the end.",
  "Believe in yourself and your abilities.",
  "Consistency creates extraordinary results.",
  "Every expert was once a beginner.",
  "Success begins outside your comfort zone.",
  "Learn something new every day.",
  "Be stronger than your excuses.",
  "Great things take time.",
  "Your future is created by what you do today.",
  "Difficult roads often lead to beautiful destinations.",
  "Take the risk or lose the chance.",
  "Action is the foundation of success.",
  "Stay hungry, stay curious.",
  "Progress over perfection.",
  "The harder you work, the luckier you get.",
  "Focus on the goal, not the obstacles.",
  "Turn your dreams into plans.",
  "Every day is a fresh start.",
  "Success starts with self-belief.",
  "Keep learning, keep growing.",
  "Do it with passion or not at all.",
  "Winners never quit, and quitters never win.",
  "The journey matters as much as the destination.",
  "Push yourself because no one else will.",
  "One step at a time is enough.",
  "Don't fear failure; fear not trying.",
  "Your attitude determines your direction.",
  "Patience is the key to mastery.",
  "Work in silence, let success make the noise.",
  "Stay positive and keep moving forward.",
  "Every challenge is an opportunity to grow.",
  "You are capable of amazing things.",
  "Start where you are, use what you have.",
  "Success is earned, not given.",
  "Never stop improving yourself.",
  "Make today count.",
  "Confidence comes from preparation.",
  "Be fearless in the pursuit of your goals.",
  "Stay committed to your vision.",
  "Nothing changes unless you do.",
  "The only way to fail is to stop trying.",
];

const btn = document.querySelector("button");
const element = document.querySelector("h1");

btn.addEventListener("click", () => {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  element.textContent = quotes[randomIndex];
});
