const Users = [
  {
    name: "Rohit Negi",
    accountNumber: 1001,
    city: "Dehradun",
    age: 25,
    balance: 5000,
    accountType: "saving",
  },
  {
    name: "Mohit Sharma",
    accountNumber: 1002,
    city: "Delhi",
    age: 22,
    balance: 15000,
    accountType: "current",
  },
  {
    name: "Aman Verma",
    accountNumber: 1003,
    city: "Delhi",
    age: 28,
    balance: 25000,
    accountType: "saving",
  },
  {
    name: "Priya Singh",
    accountNumber: 1004,
    city: "Mumbai",
    age: 24,
    balance: 32000,
    accountType: "saving",
  },
  {
    name: "Neha Gupta",
    accountNumber: 1005,
    city: "Bangalore",
    age: 27,
    balance: 18000,
    accountType: "current",
  },
  {
    name: "Rahul Mehta",
    accountNumber: 1006,
    city: "Pune",
    age: 31,
    balance: 45000,
    accountType: "saving",
  },
  {
    name: "Ankit Kumar",
    accountNumber: 1007,
    city: "Noida",
    age: 26,
    balance: 7000,
    accountType: "saving",
  },
  {
    name: "Sneha Joshi",
    accountNumber: 1008,
    city: "Jaipur",
    age: 23,
    balance: 12000,
    accountType: "current",
  },
  {
    name: "Vikas Yadav",
    accountNumber: 1009,
    city: "Lucknow",
    age: 35,
    balance: 60000,
    accountType: "saving",
  },
  {
    name: "Pooja Rawat",
    accountNumber: 1010,
    city: "Dehradun",
    age: 29,
    balance: 9000,
    accountType: "saving",
  },

  {
    name: "Saurabh Jain",
    accountNumber: 1011,
    city: "Delhi",
    age: 33,
    balance: 52000,
    accountType: "current",
  },
  {
    name: "Kavita Mishra",
    accountNumber: 1012,
    city: "Mumbai",
    age: 30,
    balance: 41000,
    accountType: "saving",
  },
  {
    name: "Deepak Bisht",
    accountNumber: 1013,
    city: "Haldwani",
    age: 24,
    balance: 8000,
    accountType: "saving",
  },
  {
    name: "Riya Kapoor",
    accountNumber: 1014,
    city: "Chandigarh",
    age: 21,
    balance: 3000,
    accountType: "saving",
  },
  {
    name: "Harsh Agarwal",
    accountNumber: 1015,
    city: "Bangalore",
    age: 32,
    balance: 75000,
    accountType: "current",
  },
  {
    name: "Nikhil Bansal",
    accountNumber: 1016,
    city: "Gurgaon",
    age: 28,
    balance: 27000,
    accountType: "saving",
  },
  {
    name: "Isha Pandey",
    accountNumber: 1017,
    city: "Pune",
    age: 26,
    balance: 22000,
    accountType: "saving",
  },
  {
    name: "Manish Thakur",
    accountNumber: 1018,
    city: "Shimla",
    age: 38,
    balance: 85000,
    accountType: "current",
  },
  {
    name: "Swati Saxena",
    accountNumber: 1019,
    city: "Kanpur",
    age: 25,
    balance: 11000,
    accountType: "saving",
  },
  {
    name: "Arjun Rana",
    accountNumber: 1020,
    city: "Dehradun",
    age: 34,
    balance: 39000,
    accountType: "current",
  },

  {
    name: "Tanya Malhotra",
    accountNumber: 1021,
    city: "Delhi",
    age: 23,
    balance: 16000,
    accountType: "saving",
  },
  {
    name: "Rakesh Chauhan",
    accountNumber: 1022,
    city: "Meerut",
    age: 41,
    balance: 95000,
    accountType: "saving",
  },
  {
    name: "Simran Kaur",
    accountNumber: 1023,
    city: "Amritsar",
    age: 27,
    balance: 34000,
    accountType: "current",
  },
  {
    name: "Yash Rajput",
    accountNumber: 1024,
    city: "Jaipur",
    age: 22,
    balance: 6500,
    accountType: "saving",
  },
  {
    name: "Komal Arora",
    accountNumber: 1025,
    city: "Noida",
    age: 29,
    balance: 47000,
    accountType: "saving",
  },
  {
    name: "Abhishek Tiwari",
    accountNumber: 1026,
    city: "Lucknow",
    age: 36,
    balance: 72000,
    accountType: "current",
  },
  {
    name: "Megha Soni",
    accountNumber: 1027,
    city: "Indore",
    age: 24,
    balance: 14000,
    accountType: "saving",
  },
  {
    name: "Varun Nair",
    accountNumber: 1028,
    city: "Kochi",
    age: 31,
    balance: 56000,
    accountType: "saving",
  },
  {
    name: "Anjali Das",
    accountNumber: 1029,
    city: "Kolkata",
    age: 28,
    balance: 26000,
    accountType: "current",
  },
  {
    name: "Gaurav Saini",
    accountNumber: 1030,
    city: "Delhi",
    age: 30,
    balance: 31000,
    accountType: "saving",
  },

  {
    name: "Mansi Khanna",
    accountNumber: 1031,
    city: "Mumbai",
    age: 26,
    balance: 21000,
    accountType: "saving",
  },
  {
    name: "Kunal Seth",
    accountNumber: 1032,
    city: "Bangalore",
    age: 34,
    balance: 64000,
    accountType: "current",
  },
  {
    name: "Divya Sharma",
    accountNumber: 1033,
    city: "Pune",
    age: 25,
    balance: 17000,
    accountType: "saving",
  },
  {
    name: "Prateek Goyal",
    accountNumber: 1034,
    city: "Gurgaon",
    age: 37,
    balance: 88000,
    accountType: "saving",
  },
  {
    name: "Nisha Rawat",
    accountNumber: 1035,
    city: "Dehradun",
    age: 22,
    balance: 4500,
    accountType: "saving",
  },
  {
    name: "Aakash Malik",
    accountNumber: 1036,
    city: "Chandigarh",
    age: 29,
    balance: 29000,
    accountType: "current",
  },
  {
    name: "Sakshi Jain",
    accountNumber: 1037,
    city: "Jaipur",
    age: 27,
    balance: 24000,
    accountType: "saving",
  },
  {
    name: "Rohan Kapoor",
    accountNumber: 1038,
    city: "Delhi",
    age: 33,
    balance: 53000,
    accountType: "saving",
  },
  {
    name: "Pankaj Negi",
    accountNumber: 1039,
    city: "Haldwani",
    age: 40,
    balance: 97000,
    accountType: "current",
  },
  {
    name: "Shreya Gupta",
    accountNumber: 1040,
    city: "Noida",
    age: 23,
    balance: 12500,
    accountType: "saving",
  },

  {
    name: "Aditya Joshi",
    accountNumber: 1041,
    city: "Dehradun",
    age: 28,
    balance: 36000,
    accountType: "saving",
  },
  {
    name: "Bhavna Singh",
    accountNumber: 1042,
    city: "Mumbai",
    age: 35,
    balance: 68000,
    accountType: "current",
  },
  {
    name: "Chetan Kumar",
    accountNumber: 1043,
    city: "Lucknow",
    age: 30,
    balance: 33000,
    accountType: "saving",
  },
  {
    name: "Devika Rao",
    accountNumber: 1044,
    city: "Hyderabad",
    age: 26,
    balance: 19000,
    accountType: "saving",
  },
  {
    name: "Eshan Bhatia",
    accountNumber: 1045,
    city: "Delhi",
    age: 24,
    balance: 10000,
    accountType: "saving",
  },
  {
    name: "Farhan Khan",
    accountNumber: 1046,
    city: "Bhopal",
    age: 32,
    balance: 58000,
    accountType: "current",
  },
  {
    name: "Garima Verma",
    accountNumber: 1047,
    city: "Indore",
    age: 29,
    balance: 42000,
    accountType: "saving",
  },
  {
    name: "Himanshu Pandey",
    accountNumber: 1048,
    city: "Kanpur",
    age: 36,
    balance: 81000,
    accountType: "saving",
  },
  {
    name: "Irfan Ali",
    accountNumber: 1049,
    city: "Kolkata",
    age: 31,
    balance: 49000,
    accountType: "current",
  },
  {
    name: "Jaya Thakur",
    accountNumber: 1050,
    city: "Shimla",
    age: 27,
    balance: 23000,
    accountType: "saving",
  },

  {
    name: "Kartik Sharma",
    accountNumber: 1051,
    city: "Delhi",
    age: 22,
    balance: 7500,
    accountType: "saving",
  },
  {
    name: "Lavanya Iyer",
    accountNumber: 1052,
    city: "Chennai",
    age: 34,
    balance: 61000,
    accountType: "current",
  },
  {
    name: "Mukul Arora",
    accountNumber: 1053,
    city: "Noida",
    age: 28,
    balance: 28000,
    accountType: "saving",
  },
  {
    name: "Naveen Rawal",
    accountNumber: 1054,
    city: "Dehradun",
    age: 39,
    balance: 92000,
    accountType: "saving",
  },
  {
    name: "Ojasvi Sinha",
    accountNumber: 1055,
    city: "Patna",
    age: 25,
    balance: 13500,
    accountType: "saving",
  },
  {
    name: "Parth Chawla",
    accountNumber: 1056,
    city: "Gurgaon",
    age: 30,
    balance: 46000,
    accountType: "current",
  },
  {
    name: "Qadir Hussain",
    accountNumber: 1057,
    city: "Lucknow",
    age: 33,
    balance: 57000,
    accountType: "saving",
  },
  {
    name: "Ritika Kapoor",
    accountNumber: 1058,
    city: "Mumbai",
    age: 26,
    balance: 20000,
    accountType: "saving",
  },
  {
    name: "Siddharth Jain",
    accountNumber: 1059,
    city: "Jaipur",
    age: 37,
    balance: 83000,
    accountType: "current",
  },
  {
    name: "Tanvi Mehra",
    accountNumber: 1060,
    city: "Delhi",
    age: 24,
    balance: 15500,
    accountType: "saving",
  },

  {
    name: "Uday Singh",
    accountNumber: 1061,
    city: "Chandigarh",
    age: 29,
    balance: 37000,
    accountType: "saving",
  },
  {
    name: "Vaishali Gupta",
    accountNumber: 1062,
    city: "Pune",
    age: 31,
    balance: 54000,
    accountType: "current",
  },
  {
    name: "Waseem Khan",
    accountNumber: 1063,
    city: "Bhopal",
    age: 35,
    balance: 69000,
    accountType: "saving",
  },
  {
    name: "Yamini Joshi",
    accountNumber: 1064,
    city: "Haldwani",
    age: 23,
    balance: 9500,
    accountType: "saving",
  },
  {
    name: "Zoya Sheikh",
    accountNumber: 1065,
    city: "Hyderabad",
    age: 27,
    balance: 26000,
    accountType: "current",
  },
  {
    name: "Anmol Rathi",
    accountNumber: 1066,
    city: "Indore",
    age: 32,
    balance: 51000,
    accountType: "saving",
  },
  {
    name: "Bhawna Rawat",
    accountNumber: 1067,
    city: "Dehradun",
    age: 28,
    balance: 30500,
    accountType: "saving",
  },
  {
    name: "Chirag Bansal",
    accountNumber: 1068,
    city: "Noida",
    age: 34,
    balance: 76000,
    accountType: "current",
  },
  {
    name: "Disha Saini",
    accountNumber: 1069,
    city: "Delhi",
    age: 21,
    balance: 4000,
    accountType: "saving",
  },
  {
    name: "Ekta Malhotra",
    accountNumber: 1070,
    city: "Mumbai",
    age: 30,
    balance: 44000,
    accountType: "saving",
  },

  {
    name: "Faisal Ansari",
    accountNumber: 1071,
    city: "Kolkata",
    age: 38,
    balance: 99000,
    accountType: "current",
  },
  {
    name: "Geetika Arora",
    accountNumber: 1072,
    city: "Gurgaon",
    age: 26,
    balance: 18500,
    accountType: "saving",
  },
  {
    name: "Hardik Mehta",
    accountNumber: 1073,
    city: "Bangalore",
    age: 33,
    balance: 73000,
    accountType: "saving",
  },
  {
    name: "Ishita Sharma",
    accountNumber: 1074,
    city: "Pune",
    age: 24,
    balance: 14500,
    accountType: "saving",
  },
  {
    name: "Jatin Yadav",
    accountNumber: 1075,
    city: "Lucknow",
    age: 36,
    balance: 67000,
    accountType: "current",
  },
  {
    name: "Kirti Negi",
    accountNumber: 1076,
    city: "Dehradun",
    age: 25,
    balance: 21500,
    accountType: "saving",
  },
  {
    name: "Lakshay Gupta",
    accountNumber: 1077,
    city: "Delhi",
    age: 29,
    balance: 38500,
    accountType: "saving",
  },
  {
    name: "Meenakshi Rao",
    accountNumber: 1078,
    city: "Chennai",
    age: 31,
    balance: 59000,
    accountType: "current",
  },
  {
    name: "Nitin Saxena",
    accountNumber: 1079,
    city: "Kanpur",
    age: 40,
    balance: 91000,
    accountType: "saving",
  },
  {
    name: "Oorja Kapoor",
    accountNumber: 1080,
    city: "Jaipur",
    age: 22,
    balance: 8500,
    accountType: "saving",
  },

  {
    name: "Pranav Joshi",
    accountNumber: 1081,
    city: "Haldwani",
    age: 27,
    balance: 27500,
    accountType: "saving",
  },
  {
    name: "Radhika Jain",
    accountNumber: 1082,
    city: "Noida",
    age: 30,
    balance: 43000,
    accountType: "current",
  },
  {
    name: "Sameer Khan",
    accountNumber: 1083,
    city: "Bhopal",
    age: 35,
    balance: 62500,
    accountType: "saving",
  },
  {
    name: "Trisha Singh",
    accountNumber: 1084,
    city: "Delhi",
    age: 23,
    balance: 11500,
    accountType: "saving",
  },
  {
    name: "Utkarsh Rawat",
    accountNumber: 1085,
    city: "Dehradun",
    age: 32,
    balance: 50500,
    accountType: "current",
  },
  {
    name: "Vidhi Arora",
    accountNumber: 1086,
    city: "Mumbai",
    age: 28,
    balance: 35500,
    accountType: "saving",
  },
  {
    name: "Wasim Qureshi",
    accountNumber: 1087,
    city: "Hyderabad",
    age: 37,
    balance: 87000,
    accountType: "saving",
  },
  {
    name: "Yogesh Kumar",
    accountNumber: 1088,
    city: "Patna",
    age: 34,
    balance: 74000,
    accountType: "current",
  },
  {
    name: "Zainab Ali",
    accountNumber: 1089,
    city: "Kolkata",
    age: 26,
    balance: 24500,
    accountType: "saving",
  },
  {
    name: "Aarav Bhatia",
    accountNumber: 1090,
    city: "Gurgaon",
    age: 24,
    balance: 17500,
    accountType: "saving",
  },

  {
    name: "Bhavesh Jain",
    accountNumber: 1091,
    city: "Indore",
    age: 39,
    balance: 96500,
    accountType: "current",
  },
  {
    name: "Charu Mishra",
    accountNumber: 1092,
    city: "Lucknow",
    age: 27,
    balance: 29500,
    accountType: "saving",
  },
  {
    name: "Dhruv Malhotra",
    accountNumber: 1093,
    city: "Delhi",
    age: 31,
    balance: 57500,
    accountType: "saving",
  },
  {
    name: "Esha Kapoor",
    accountNumber: 1094,
    city: "Pune",
    age: 25,
    balance: 20500,
    accountType: "saving",
  },
  {
    name: "Faizan Sheikh",
    accountNumber: 1095,
    city: "Bangalore",
    age: 33,
    balance: 71500,
    accountType: "current",
  },
  {
    name: "Gunjan Rawat",
    accountNumber: 1096,
    city: "Dehradun",
    age: 29,
    balance: 33500,
    accountType: "saving",
  },
  {
    name: "Hemant Verma",
    accountNumber: 1097,
    city: "Noida",
    age: 36,
    balance: 80500,
    accountType: "saving",
  },
  {
    name: "Isha Bansal",
    accountNumber: 1098,
    city: "Jaipur",
    age: 22,
    balance: 10500,
    accountType: "saving",
  },
  {
    name: "Jayant Soni",
    accountNumber: 1099,
    city: "Mumbai",
    age: 38,
    balance: 93500,
    accountType: "current",
  },
  {
    name: "Kritika Sharma",
    accountNumber: 1100,
    city: "Delhi",
    age: 26,
    balance: 26500,
    accountType: "saving",
  },
];

export default Users;
